name: Build

on:
    push:
        branches:
            - master
        paths:
            - '**.java'
    pull_request:
        branches:
            - master
        paths:
            - '**.java'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 11.0.7
            - run: mvn -B package --file pom.xml
